# SPDX-FileCopyrightText: PyPSA-SPICE Developers

# SPDX-License-Identifier: GPL-2.0-or-later

# coding: utf-8

# Base configuration includes paths and general settings which are not relevant to the scenario settings or model constraints.

version: 0.1.0

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

#####Init settings#####
path_configs:
  data_folder_name: mod-data-th-pdp
  project_name: TH_PDP_v2-2026_fillin_test
  input_scenario_name: pdp_high
  output_scenario_name: pdp_high
  
base_configs:
  regions:
    TH: ["BKK", "BKKNR", "EA", "NE", "NR", "SO", "WE"]
  years: [2026, 2030, 2035, 2040, 2045, 2050] # list of modelled years
  sector: ["p"] # options: ["p", "p-i", "p-t", "p-i-t"], representing power (p), industry (i), and transport (t) sectors.
  currency: USD # currency for the model in all uppercases, ISO4217 format
